### ISSUE TITLE
[CI] oss:cutlass-rel and qa_py_test:9.24.0.43_13.3.0 jobs fail set_name_prefix remove_cutlass_symbol with DSL 4.5.1

### ISSUE THREAD

**Issue by liujane-dev** [NVIDIA/cudnn-frontend#882]
## Summary

Four `oss:cutlass-rel` jobs regressed in scheduled develop pipeline #65838340. The common failure is `TypeError: BaseDSL.jit_runner.<locals>.jit_runner_decorator.<locals>.set_name_prefix() got an unexpected keyword argument 'remove_cutlass_symbol'`, either raised directly or wrapped in an optional-dependency `ImportError` by GEMM / grouped-GEMM wrappers.

The failure is shared across SM100 shards, SM80, and SM90 release-lane jobs because these lanes install `nvidia-cudnn-frontend[cutedsl]` with `nvidia-cutlass-dsl==4.5.1`, while current FE code calls `set_name_prefix(..., remove_cutlass_symbol=True)`, which is not accepted by that DSL API.

## CI jobs

- Current bad: [#422422671](https://nv/cudnn_frontend/-/jobs/422422671) (`oss:cutlass-rel:sm100-shard0`), 70 failed / 4 errors
- Previous same-lane good anchor: [#420763982](https://nv/cudnn_frontend/-/jobs/420763982) in pipeline #65642908
- Current bad: [#422422673](https://nv/cudnn_frontend/-/jobs/422422673) (`oss:cutlass-rel:sm100-shard1`), 135 failed / 4 errors
- Previous same-lane good anchor: [#420763984](https://nv/cudnn_frontend/-/jobs/420763984) in pipeline #65642908
- Current bad: [#422422669](https://nv/cudnn_frontend/-/jobs/422422669) (`oss:cutlass-rel:sm80`), 39 failed / 4 errors
- Previous same-lane good anchor: [#420763979](https://nv/cudnn_frontend/-/jobs/420763979) in pipeline #65642908
- Current bad: [#422422670](https://nv/cudnn_frontend/-/jobs/422422670) (`oss:cutlass-rel:sm90`), 39 failed / 4 errors
- Previous same-lane good anchor: [#420763981](https://nv/cudnn_frontend/-/jobs/420763981) in pipeline #65642908
- Current pipeline: [#65838340](https://nv/cudnn_frontend/-/pipelines/65838340)

## Versions

- Ref: `develop`
- FE good -> bad: `f2e3c982` -> `5bb72897`
- cuDNN backend: `9.26.0` / `92600`
- Python: `3.12.3`
- Affected lanes: `oss:cutlass-rel:sm100-shard0`, `oss:cutlass-rel:sm100-shard1`, `oss:cutlass-rel:sm80`, `oss:cutlass-rel:sm90`
- Release-lane Cutlass DSL package: `nvidia-cutlass-dsl==4.5.1`

## Failing tests

Representative failures include:

```text
test/python/fe_api/gemm/test_gemm_proj_rope_mxfp8.py::test_gemm_proj_rope_mxfp8_reference_contract[False-128]
test/python/fe_api/gemm/test_gemm_srelu.py::test_gemm_srelu_compile_execute_fp4[...]
test/python/fe_api/gemm/test_gemm_dsrelu.py::test_gemm_dsrelu_compile_execute_fp4[...]
test/python/fe_api/grouped_gemm/test_grouped_gemm_dglu.py::test_grouped_gemm_dglu_discrete_wrapper_alpha_dgeglu[1.0]
test/python/fe_api/grouped_gemm/test_grouped_gemm_wgrad.py::test_grouped_gemm_wgrad_dense_compile_execute_fp4[...]
test/python/fe_api/test_rubin_kernel_dispatch.py::test_grouped_gemm_wgrad_rubin_quantization_validation[...]
```

Stable error signature:

```text
TypeError: BaseDSL.jit_runner.<locals>.jit_runner_decorator.<locals>.set_name_prefix() got an unexpected keyword argument 'remove_cutlass_symbol'
```

Wrapped ImportError variant:

```text
ImportError: <wrapper> requires optional dependencies. Install with 'pip install nvidia-cudnn-frontend[cutedsl]': BaseDSL.jit_runner.<locals>.jit_runner_decorator.<locals>.set_name_prefix() got an unexpected keyword argument 'remove_cutlass_symbol'
```

## Culprit

- Repo: `cudnn_frontend`
- Culprit commit: `bfa27252`
- Title: `frost: prefix GEMM and SDPA kernel symbols with cudnn (#854)`
- Evidence: `git log -S'remove_cutlass_symbol'` points to this commit, and `git grep` at FE `5bb72897` shows many GEMM Cutlass DSL kernels now calling `kernel.set_name_prefix("cudnn", remove_cutlass_symbol=True)`.

## Root cause analysis

Commit `bfa27252` updated FE GEMM / grouped-GEMM Cutlass DSL kernels to call `set_name_prefix("cudnn", remove_cutlass_symbol=True)` so generated kernel symbols are prefixed with `cudnn`. The `oss:cutlass-rel` lanes install `nvidia-cudnn-frontend[cutedsl]` with `nvidia-cutlass-dsl==4.5.1`; that release DSL's `set_name_prefix` callable does not accept the new `remove_cutlass_symbol` keyword. Importing or compiling the affected kernels therefore fails before the tests can run, producing broad direct `TypeError`s and wrapper-level optional-dependency `ImportError`s.

This is a FE/DSL compatibility regression: FE code now assumes a newer Cutlass DSL API than the `cutlass-rel` CI environment provides.

## Suggested fix

- Either raise the minimum `nvidia-cutlass-dsl` version used by `oss:cutlass-rel` / `nvidia-cudnn-frontend[cutedsl]` to a build that supports `remove_cutlass_symbol`, or guard the keyword by checking DSL API support.
- If the symbol-prefix change must remain compatible with DSL 4.5.1, call `set_name_prefix("cudnn")` on old DSL versions and only pass `remove_cutlass_symbol=True` where supported.
- Add an import-boundary or smoke test in the release-lane dependency set so future FE code does not silently require a newer DSL API.

**Comment by liujane-dev** [comment]
Verified fixed in FE pipeline [#66375696](https://nv/cudnn_frontend/-/pipelines/66375696) and [#66489137](https://nv/cudnn_frontend/-/pipelines/66489137).

  The original TypeError from the oss:cutlass-rel jobs is no longer observed: set_name_prefix() got an unexpected keyword argument 'remove_cutlass_symbol'.

  Root cause was the release-lane CI pinning nvidia-cutlass-dsl==4.5.1 while FE code used the newer set_name_prefix(..., remove_cutlass_symbol=True) API.

  Fixed by 39d87573 ("ci: drop the cutlass-dsl 4.5.x pin and the Python 3.9 wheels"), which moves the oss cutlass-rel default to nvidia-cutlass-dsl==4.6.2. The remaining failures in pipeline #66489137 are unrelated to the original remove_cutlass_symbol signature.
